import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every build and is gitignored;
    // its triple-slash references are not ours to fix. `.claude/` holds the
    // vendored impeccable plugin, which is third-party and not ours to lint.
    ignores: [
      "out/**",
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      ".claude/**",
      ".impeccable/**",
    ],
  },
];

export default eslintConfig;
